kind: Deployment
apiVersion: apps/v1
metadata:
  name: currency-deploy
  namespace: nginx-namespace
  labels:
    app: nginx-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      name: deployment-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: deploy-currency
          image: thesahilsuman/currency-c:latest
          ports:
            - containerPort: 80
