kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: nginx-namespace
spec:
  type: ClusterIP
  selector:
    app: nginx-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
     #  nodePort: 30505  # range of 30000-32100
